AWSTemplateFormatVersion: 2010-09-09
Description: Template to provision multi node kubernetes cluster
Parameters:
  VPCStack: 
    Description: "VPC Cloudformation stack name (Example:- cf-vpc-multiaz-hybrid, Option type: Mandatory)"
    Type: String
    MinLength: 1
    Default: cf-vpc-multiaz-hybrid
  EKSVersion:
    Description: "Specify Kubernetes Version (Example:- 1.20 Option type: Mandatory)"
    Type: String
    Default: '1.20'
    MinLength: 1
  EKSControlplaneSG:
    Description: "Specify ClusterControlPlane Security Group stack export name (Example:- cf-security-groups)"
    Type: String
    MinLength: 1
    Default: cf-security-groups
Resources:
  HyphenClusterNodeIAMRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - eks.amazonaws.com
            Action:
            - sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
          - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  HyphenKubernetesCluster:
      Type: AWS::EKS::Cluster
      Properties:
        Version: !Ref EKSVersion 
        RoleArn: !GetAtt HyphenClusterNodeIAMRole.Arn
        Name: 'HyphenKubernetesCluster'
        ResourcesVpcConfig:
          SecurityGroupIds:
            - Fn::ImportValue: !Sub "${EKSControlplaneSG}-ControlPlaneSGID"
          SubnetIds:
            - Fn::ImportValue: !Sub "${VPCStack}-PrivateSubnet1"
            - Fn::ImportValue: !Sub "${VPCStack}-PrivateSubnet2"
            - Fn::ImportValue: !Sub "${VPCStack}-PrivateSubnet3"
            - Fn::ImportValue: !Sub "${VPCStack}-PublicSubnet1"
            - Fn::ImportValue: !Sub "${VPCStack}-PublicSubnet2"
            - Fn::ImportValue: !Sub "${VPCStack}-PublicSubnet3"